### ISSUE TITLE
NoMethodError: undefined method `config' for nil:NilClass

### ISSUE THREAD

**Issue by krsyoung** [harled/matey#57]
I'm current facing an issue trying to run matey:

```
NoMethodError: undefined method `config' for nil:NilClass

          /(.*#{Regexp.quote(Rails.application.config.view_component.view_component_path)})|(\.rb)/, ""
                                              ^^^^^^^
/usr/local/bundle/gems/view_component-2.66.0/lib/view_component/base.rb:499:in `inherited'
/usr/local/bundle/bundler/gems/matey-0da56ccf8b95/app/components/application_component.rb:4:in `<main>'
/usr/local/bundle/bundler/gems/matey-0da56ccf8b95/lib/matey.rb:5:in `require_relative'
/usr/local/bundle/bundler/gems/matey-0da56ccf8b95/lib/matey.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `each'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `block in require'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `each'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `require'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler.rb:188:in `require'
/app/config/application.rb:7:in `<main>'
/app/rakefile:4:in `require_relative'
/app/rakefile:4:in `<main>'
/usr/local/bundle/gems/railties-7.0.3.1/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/usr/local/bundle/gems/railties-7.0.3.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/local/bundle/gems/railties-7.0.3.1/lib/rails/command.rb:51:in `invoke'
/usr/local/bundle/gems/railties-7.0.3.1/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

It seems to be an issue related to an underlying change with `view_components` and how the library is included in this gem (vs a rails app).

**Comment by caitmich** [comment]
@krsyoung do you have any repro steps?

**Comment by pJeyakumar** [comment]
@caitmich you'll need to change the view_component version to 2.66.0 in the Gemfile.lock, remove the version of the view_component in the Gemfile. Then run the application and you'll get the error

**Comment by pJeyakumar** [comment]
This is an issue since at this point we have not created our Rails Application yet (meaning we cant call Rails.application), it is being resolved [here](https://github.com/github/view_component/issues/1464)

**Comment by boardfish** [comment]
Hey folks! Would you like to try pointing it at [this branch](https://github.com/github/view_component/pull/1466) and dropping a review on the PR depending on your success? I don't have Docker installed on my personal machine, so it might be easier for you to do it. Thanks, and apologies! 🙏
